import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { ensureDir, fail, output, parseArgs, round3 } from "./util.mjs";

function esc(s) {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function img(outDir, path, alt) {
  return `<figure><img src="${esc(relative(outDir, path))}" alt="${esc(alt)}" loading="lazy"><figcaption>${esc(alt)}</figcaption></figure>`;
}

export async function main(argv) {
  const args = parseArgs(argv, { manifest: "string", out: "string", title: "string" });
  const manifestPath = args.manifest ?? "edit.json";
  if (!existsSync(manifestPath)) fail(`Manifest not found: ${manifestPath}. Run /ripple plan first.`, 2);
  const baseDir = dirname(resolve(manifestPath));
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));

  const outPath = resolve(args.out ?? join(baseDir, "qa", "review.html"));
  const outDir = ensureDir(dirname(outPath));
  const title = args.title ?? manifest.title ?? "Edit review";

  // Gather artifacts.
  const candidatesDir = join(baseDir, "work", "candidates");
  const sheetsDir = join(baseDir, "qa", "frame-sheets");
  const gradesSheet = join(baseDir, "qa", "grades", "grade_contact.jpg");
  const qaDir = join(baseDir, ".ripple", "qa");
  const snapshots = existsSync(qaDir)
    ? readdirSync(qaDir).filter((f) => f.startsWith("qa-")).sort().slice(-5)
        .map((f) => JSON.parse(readFileSync(join(qaDir, f), "utf8")))
    : [];
  const latest = snapshots[snapshots.length - 1] ?? null;

  const sceneRows = (manifest.scenes ?? []).map((s) => {
    const dur = round3(s.end - s.start);
    return `<tr>
      <td class="mono">${esc(s.slug)}</td>
      <td>${esc(s.title ?? s.card ?? "")}</td>
      <td class="mono num">${s.start}</td>
      <td class="mono num">${s.end}</td>
      <td class="mono num">${dur}s</td>
      <td><span class="chip ${esc(s.status)}">${esc(s.status)}</span></td>
      <td class="dim">${esc(s.reasoning ?? "")}${s.expectEnding ? `<br><span class="mono dim">ends: “${esc(s.expectEnding)}”</span>` : ""}</td>
    </tr>`;
  }).join("\n");

  const stripFigures = (manifest.scenes ?? []).flatMap((s) => {
    const figs = [];
    for (const kind of ["head", "tail"]) {
      const p = join(candidatesDir, `${s.slug}_${kind}.jpg`);
      if (existsSync(p)) figs.push(img(outDir, p, `${s.slug} — ${kind} frames`));
    }
    return figs;
  }).join("\n");

  const sheetFigures = existsSync(sheetsDir)
    ? readdirSync(sheetsDir).filter((f) => f.endsWith(".jpg")).sort()
        .map((f) => img(outDir, join(sheetsDir, f), `frame sheet — ${f}`)).join("\n")
    : "";

  const qaRows = latest
    ? latest.checks.map((c) =>
        `<tr><td class="mono">${esc(c.id)}</td><td><span class="chip ${c.ok ? "pass" : "fail"}">${c.ok ? "PASS" : "FAIL"}</span></td><td class="dim">${esc(typeof c.detail === "string" ? c.detail : JSON.stringify(c.detail))}</td></tr>`
      ).join("\n")
    : "";
  const trendLine = snapshots.map((s) => `${s.passed}/${s.total}`).join(" → ");

  const html = `<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} — ripple review</title>
<style>
  :root { color-scheme: dark; }
  body { background:#14161b; color:#e7e5df; font:15px/1.55 -apple-system,BlinkMacSystemFont,sans-serif; margin:0; }
  .wrap { max-width:1000px; margin:0 auto; padding:40px 24px 80px; }
  h1 { font-size:26px; margin:0 0 4px; } h2 { font-size:18px; margin:40px 0 12px; }
  .sub { color:#9aa0aa; margin:0 0 24px; }
  .mono { font-family:"SF Mono",ui-monospace,Menlo,monospace; font-size:12.5px; }
  .num { text-align:right; font-variant-numeric:tabular-nums; }
  .dim { color:#9aa0aa; font-size:13px; }
  table { border-collapse:collapse; width:100%; }
  th { text-align:left; font-size:11px; letter-spacing:.08em; color:#6b7078; padding:6px 12px 6px 0; border-bottom:1px solid #2a2e38; }
  td { padding:8px 12px 8px 0; border-bottom:1px solid #2a2e38; vertical-align:top; }
  .chip { font-family:"SF Mono",ui-monospace,monospace; font-size:10.5px; padding:1px 7px; border-radius:3px; border:1px solid; }
  .chip.locked, .chip.pass { color:#7fb069; border-color:#7fb06966; }
  .chip.proposed { color:#d9a54a; border-color:#d9a54a66; }
  .chip.repaired { color:#6a9ec9; border-color:#6a9ec966; }
  .chip.fail { color:#c97a6a; border-color:#c97a6a66; }
  figure { margin:0 0 16px; } figcaption { color:#6b7078; font-size:12px; margin-top:4px; }
  img { max-width:100%; border-radius:4px; border:1px solid #2a2e38; }
  .scroll { overflow-x:auto; }
</style>
<div class="wrap">
  <h1>${esc(title)}</h1>
  <p class="sub">Generated by <span class="mono">ripple review</span> · color policy: <span class="mono">${esc(manifest.color?.policy ?? "unset")}</span>${manifest.grade?.name ? ` · grade: <span class="mono">${esc(manifest.grade.name)}</span>` : ""}</p>

  <h2>Cut list</h2>
  <div class="scroll"><table>
    <tr><th>SCENE</th><th>CARD / TITLE</th><th>IN</th><th>OUT</th><th>DUR</th><th>STATUS</th><th>REASONING</th></tr>
    ${sceneRows}
  </table></div>

  ${latest ? `<h2>QA — latest run ${esc(latest.passed)}/${esc(String(latest.total))}${trendLine ? ` <span class="dim mono">(trend: ${esc(trendLine)})</span>` : ""}</h2>
  <div class="scroll"><table><tr><th>CHECK</th><th>RESULT</th><th>DETAIL</th></tr>${qaRows}</table></div>` : ""}

  ${existsSync(gradesSheet) ? `<h2>Grade variants</h2>${img(outDir, gradesSheet, "grade comparison (same frame)")}` : ""}

  ${stripFigures ? `<h2>Cut-point evidence</h2>${stripFigures}` : ""}

  ${sheetFigures ? `<h2>Frame sheets</h2>${sheetFigures}` : ""}
</div>
`;

  writeFileSync(outPath, html);
  output({
    ok: true,
    review: outPath,
    scenes: manifest.scenes?.length ?? 0,
    qaTrend: trendLine || null,
    next: `Open it: open "${outPath}" — flag problems by scene slug; repairs stay localized.`,
  });
}
